#!/bin/sh

file="$1"
file_no_extension="${file%???}"
path="$PWD/$file"
shell=""

code () {
# Detecting if user wants to run shellcheck.
        if [ "$3" = "shellcheck" ]; then
                find "$file" | entr -rc "$shell" -c "date; shellcheck $path/$file"
	elif [ "$2" = "python3" ]; then
		find "$path" | entr -rc bash -c "date; python3 $path"
	elif [ "$2" = "go" ]; then
		find "$path" | entr -rc bash -c "date; go run ."
	elif [ "$2" = "typescript" ]; then
		find "$path" | entr -rc bash -c "date; tsc $path && node $file_no_extension.js"
        else
                find "$file" | entr -rc "$shell" -c "date; $shell $path/$file"
        fi
}


if [ -n "$2" ]; then
# Checking whether there is a shell specified by user.
        shell="$2"
# Using bash as the shell, if no shell is provided by user.
else
        shell="bash"
fi

code "$1" "$2" "$3"
