#!/bin/sh

file="$1"
path=$PWD
shell=""

code () {
# Detecting if user wants to run shellcheck.
        if [ "$3" = "shellcheck" ]; then
                find "$file" | entr -c "$shell" -c "date; shellcheck $path/$file"
        else
                find "$file" | entr -c "$shell" -c "date; $shell $path/$file"
        fi
}


if [ -n "$2" ]; then
# Checking whether there is a shell specified by user.
        shell="$2"
# Using bash as the shell, if no shell is provided by user.
else
        shell="bash"
fi

code "$1" "$2" "$3"
